plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.4'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
   sourceCompatibility = '17'
   targetCompatibility = '17'
}

repositories {
	mavenCentral()
}

// 強制所有 snakeyaml 都用標準版，移除 android classifier
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'org.yaml' && details.requested.name == 'snakeyaml') {
            details.useVersion '2.2'
            details.artifactSelection {
                selectArtifact(DependencyArtifact.DEFAULT_TYPE, null, null)
            }
        }
    }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	// Spring data jpa
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	// MySQL connector: mysql 的驅動程式
	implementation 'com.mysql:mysql-connector-j'
	// MyBatis
	implementation 'com.baomidou:mybatis-plus-spring-boot3-starter:3.5.14'
	// 加密(密文)
	implementation 'org.springframework.boot:spring-boot-starter-security'
	// HTTP
	implementation 'org.springframework.boot:spring-boot-starter-web'
	// 資料驗證
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	// openapi 線上文件
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.2'
	// Gson 依賴: 用來處理 JSON(用於LinePay)
	implementation 'com.google.code.gson:gson:2.10.1'
	// Google 提供的全球電話號碼解析與驗證工具
    implementation 'com.googlecode.libphonenumber:libphonenumber:8.13.31'
	//在修改程式碼並儲存後,Devtools 會自動偵測變更並觸發應用程式的快速重啟
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	
	// Java Faker (核心：用來產生隨機姓名、Email、地址)
	implementation('com.github.javafaker:javafaker:1.0.2') {
        exclude group: 'org.yaml', module: 'snakeyaml'
    }
    
     // 明確加回標準版（無 android classifier）
    implementation 'org.yaml:snakeyaml:2.2'
}

tasks.named('test') {
	useJUnitPlatform()
}
