spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=GMT%2B8&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

rate.api.key=${RATE_API_KEY}
ai.product.key=${AI_PRODUCT_KEY}
ai.promo.key=${AI_PROMO_KEY}

#  Spring Boot 會自動偵測 Railway 的 https，Swagger 就會用正確的協議發請求
server.forward-headers-strategy=framework